---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny    
---

```{r setup, include=FALSE}
library(flexdashboard)
```


```{r rows.print=25}
library(readxl)
library(writexl)
library(dplyr)
library(tidyr)
library(ggplot2)


xls_file <- "Artificial Lift Matrix for Commercial Production Systems (CPS)14Aug062.xlsx"

al_matrix <- read_excel(path = file.path('inst/extdata', xls_file), 
                        skip = 4, range = "C5:P63") %>% 
    rename(design_aspect = "Design Aspect")


al_matrix_tidy <- al_matrix %>% 
    gather(key = 'al_method', value = "ranking", Jet:'Chamber Lift') %>% 
    mutate(ranking = as.integer(ranking)) %>% 
    mutate(ranking = ifelse(is.na(ranking), 0, ranking)) %>% 
    mutate(relevance = case_when(
        .$al_method %in% c("ESP", "Gas Lift", "Sucker Rod Pump", "PCP") ~ "high",
        .$al_method %in% c("Jet", "ESP-CP", "Sucker Rod Pump", "PCP", "HSP") ~ "low",
        .$al_method %in% c("Metal PCP (Hi Temp)", "HGP", 
                           "Twin Screw (ESTSP)", "Twin Screw (TDTSP)", "Chamber Lift") ~ "specialty"
    )) %>% 
    mutate(relevance = as.factor(relevance)) %>% 
    mutate(ranking = as.factor(ranking))

write_xlsx(al_matrix_tidy, path = file.path('inst/extdata', "al_matrix_tidy.xlsx"))
al_matrix_tidy_orig <- al_matrix_tidy
```


# Artificial Lift Matrix

## Sidebar {.sidebar data-width="350"}

```{r}
selectInput("design_aspect", "Design Aspect of the AL", 
            choices = unique(al_matrix_tidy$design_aspect))

# renderUI({
# selectInput("value", "Value of the Design Aspect to evaluate",
#             choices = rownames(al_matrix_tidy)[al_matrix_tidy$Value %in% input$design_aspect])
# })

renderUI({
selectInput("value", "Value of the Design Aspect to evaluate",
            choices = al_matrix_tidy$Value[al_matrix_tidy$design_aspect == levels(al_matrix_tidy$design_aspect)[1]])
})

observe({
    aspect <- input$design_aspect
    updateSelectInput("value", 
                      choices = al_matrix_tidy$Value[al_matrix_tidy$design_aspect == aspect])
})    
```


## 

### Plot

```{r warning=FALSE, message=FALSE, error=FALSE}
al_matrix_tidy <- al_matrix_tidy_orig

nameorder <- make.unique(al_matrix_tidy$al_method[order(al_matrix_tidy$relevance, al_matrix_tidy$ranking)])
    
al_matrix_tidy$al_method <- factor(al_matrix_tidy$al_method, levels=nameorder)

shiny::renderPlot({
    # .design_aspect <- input$design_aspect
    # .Value <- input$value
    
    df <- subset(al_matrix_tidy, 
                 design_aspect == input$design_aspect & Value == input$value )
    
    ggplot(df, aes(x = ranking, y = al_method)) +
        geom_segment(aes(yend=al_method), xend=0, color = "grey50") +
        geom_point(size = 3, aes(colour = relevance)) +
        scale_colour_brewer(palette="Set1", limits=c("specialty","low", "high")) +
        theme_bw() +
        theme(panel.grid.major.y = element_blank()) +   # No horizontal grid lines
        facet_grid(relevance ~ ., scales="free_y", space="free_y") +
        ggtitle(paste0("by ", input$design_aspect, " when " , input$value))
    
})
```

